TeamPlanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('thelab/', include('thelab.urls')),
    path('admin/', admin.site.urls),
]

thelab/urls.py
from django.urls import path

from . import views

app_name = 'thelab'
urlpatterns = [
    path('', views.index, name='index'),
    path('calendar/<int:year>/<int:month>/', views.calendar_view, name='calendar'),
]

thelab/models.py
from django.db import models


ABSENCE_CHOICES = (
    ("HO", "Home Office"),
    ("O", "Office"),
    ("V", "Vacation"),
    ("F", "Flex Time"),
    ("PL", "Parental Leave")
)


class TeamMember(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200, blank=True)
    initials = models.CharField(max_length=10)

    def __str__(self):
        return self.initials


class Absence(models.Model):
    teammember = models.ForeignKey(TeamMember, on_delete=models.CASCADE)
    starting_date = models.DateField()
    end_date = models.DateField()
    absence_type = models.CharField(choices=ABSENCE_CHOICES, max_length=200)


class PublicHoliday(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=200, blank=True)

thelab/views.py
from django.shortcuts import render
from django.http import HttpResponse
import calendar

from .utils import Calendar
import datetime


def index(request):
    template_name = 'thelab/index.html'
    t_now = datetime.datetime.now()
    year = t_now.year
    month = t_now.month
    return render(request, template_name, {'year': year, 'month': month})


def calendar_view(request, year, month):
    template_name = 'thelab/onecolumn.html'
    mycalendar = Calendar(year, month)
    year_next, month_next = calendar._nextmonth(year, month)
    year_prev, month_prev = calendar._prevmonth(year, month)

    context_dict = {'year': year,
                    'month': month,
                    'year_next': year_next, 'month_next': month_next,
                    'year_prev': year_prev, 'month_prev': month_prev,
                    'calendar': mycalendar.formatmonth(),
                    'legend': mycalendar.get_legend()}

    return render(request, template_name, context_dict)

thelab/templates/thelab/index.html
<!DOCTYPE HTML>
<!--
	Halcyonic by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html lang="en">
    {% load static %}
	<head>
		<title>The LAB</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static  'thelab/css/main.css' %}" />
	</head>
	<body>
    {% block content %}
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">
					<div class="container">
						<div class="row">
							<div class="col-12">

								<!-- Logo -->
									<h1><a href="{% url 'thelab:index' %}" id="logo">The LAB</a></h1>

								<!-- Nav -->
									<nav id="nav">
										<a href="{% url 'thelab:index' %}">Homepage</a>
										<a href="{% url 'thelab:calendar' year month %}">View Team Calendar</a>
										<a href="">Update Calendar</a>
									</nav>

							</div>
						</div>
					</div>
					<div id="banner">
						<div class="container">
							<div class="row">
								<div class="col-6 col-12-medium">

									<!-- Banner Copy -->
										<p>The LAB: Flapping with success...</p>
										<a href="{% url 'thelab:calendar' year month %}" class="button-large">View Team Calendar</a>

								</div>
								<div class="col-6 col-12-medium imp-medium">

									<!-- Banner Image -->
										<a href="#" class="bordered-feature-image"><img src="{% static 'thelab/images/scientist.png'%}"  alt=""></a>

								</div>
							</div>
						</div>
					</div>
				</section>

			<!-- Features -->
				<section id="features">
					<div class="container">
						<div class="row">
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #1 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'thelab/images/pic01.jpg'%}" alt="" /></a>
										<h2>Welcome to Halcyonic</h2>
										<p>
											This is <strong>Halcyonic</strong>, a free site template
											by <a href="http://twitter.com/ajlkn">AJ</a> for
											<a href="http://html5up.net">HTML5 UP</a>. It's responsive,
											built on HTML5 + CSS3, and includes 5 unique page layouts.
										</p>
									</section>

							</div>
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #2 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'thelab/images/pic02.jpg'%}" alt="" /></a>
										<h2>Responsive You Say?</h2>
										<p>
											Yes! Halcyonic is built to be fully responsive so it looks great
											at every screen size, from desktops to tablets to mobile phones.
										</p>
									</section>

							</div>
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #3 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'thelab/images/pic03.jpg'%}" alt="" /></a>
										<h2>License Info</h2>
										<p>
											Halcyonic is licensed under the <a href="http://html5up.net/license">CCA</a> license,
											so use it for personal/commercial use as much as you like (just keep
											our credits intact).
										</p>
									</section>

							</div>
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #4 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'thelab/images/pic04.jpg'%}" alt="" /></a>
										<h2>Volutpat etiam aliquam</h2>
										<p>
											Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed. Suspendisse
											eu varius nibh. Suspendisse vitae magna mollis.
										</p>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Content -->
				<section id="content">
					<div class="container">
						<div class="row aln-center">
							<div class="col-4 col-12-medium">

								<!-- Box #1 -->
									<section>
										<header>
											<h2>Who We Are</h2>
											<h3>A subheading about who we are</h3>
										</header>
										<a href="#" class="feature-image"><img src="{% static 'thelab/images/pic05.jpg'%}" alt="" /></a>
										<p>
											Duis neque nisi, dapibus sed mattis quis, rutrum accumsan magna sed.
											Suspendisse eu varius nibh. Suspendisse vitae magna eget odio amet mollis
											justo facilisis quis. Sed sagittis amet lorem ipsum.
										</p>
									</section>

							</div>
							<div class="col-4 col-6-medium col-12-small">

								<!-- Box #2 -->
									<section>
										<header>
											<h2>What We Do</h2>
											<h3>A subheading about what we do</h3>
										</header>
										<ul class="check-list">
											<li>Sed mattis quis rutrum accum</li>
											<li>Eu varius nibh suspendisse lorem</li>
											<li>Magna eget odio amet mollis justo</li>
											<li>Facilisis quis sagittis mauris</li>
											<li>Amet tellus gravida lorem ipsum</li>
										</ul>
									</section>

							</div>
							<div class="col-4 col-6-medium col-12-small">

								<!-- Box #3 -->
									<section>
										<header>
											<h2>What People Are Saying</h2>
											<h3>And a final subheading about our clients</h3>
										</header>
										<ul class="quote-list">
											<li>
												<img src="{% static 'thelab/images/pic06.jpg'%}" alt="" />
												<p>"Neque nisidapibus mattis"</p>
												<span>Jane Doe, CEO of UntitledCorp</span>
											</li>
											<li>
												<img src="{% static 'thelab/images/pic07.jpg'%}" alt="" />
												<p>"Lorem ipsum consequat!"</p>
												<span>John Doe, President of FakeBiz</span>
											</li>
											<li>
												<img src="{% static 'thelab/images/pic08.jpg'%}" alt="" />
												<p>"Magna veroeros amet tempus"</p>
												<span>Mary Smith, CFO of UntitledBiz</span>
											</li>
										</ul>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Footer -->
				<section id="footer">
					<div class="container">
						<div class="row">
							<div class="col-8 col-12-medium">

								<!-- Links -->
									<section>
										<h2>Links to Important Stuff</h2>
										<div>
											<div class="row">
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
											</div>
										</div>
									</section>

							</div>
							<div class="col-4 col-12-medium imp-medium">

								<!-- Blurb -->
									<section>
										<h2>An Informative Text Blurb</h2>
										<p>
											Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed. Suspendisse eu
											varius nibh. Suspendisse vitae magna eget odio amet mollis. Duis neque nisi,
											dapibus sed mattis quis, sed rutrum accumsan sed. Suspendisse eu varius nibh
											lorem ipsum amet dolor sit amet lorem ipsum consequat gravida justo mollis.
										</p>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Copyright -->
				<div id="copyright">
					&copy; IGLAB. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
				</div>

		</div>

		<!-- Scripts -->
			<script src="{% static 'thelab/js/jquery.min.js' %}"></script>
			<script src="{% static 'thelab/js/browser.min.js' %}"></script>
			<script src="{% static 'thelab/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'thelab/js/util.js' %}"></script>
			<script src="{% static 'thelab/js/main.js' %}"></script>
    {% endblock %}
	</body>
</html>

thelab/templates/thelab/onecolumn.html
<!DOCTYPE HTML>
<!--
	Halcyonic by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html lang="en">
    {% load static %}
	<head>
		<title>The LAB - Team Calendar</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static  'thelab/css/main.css' %}" />
	</head>
	<body class="subpage">
    {% block content %}
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">
					<div class="container">
						<div class="row">
							<div class="col-12">

								<!-- Logo -->
									<h1><a href="{% url 'thelab:index' %}" id="logo">The LAB</a></h1>

								<!-- Nav -->
									<nav id="nav">
										<a href="{% url 'thelab:index' %}">Homepage</a>
										<a href="{% url 'thelab:calendar' year month %}">View Team Calendar</a>
										<a href="">Update Calendar</a>
									</nav>

							</div>
						</div>
					</div>
				</section>

			<!-- Content -->
				<section id="content">
					<div class="container">
						<div class="row">
							<div class="col-12">

								<!-- Main Content -->
									<section>
										<header>
											<h2>Team Calendar</h2>
											<h3>See everyone's absences</h3>
										</header>

                                            <p style="text-align:left;">
                                            <a href="{% url 'thelab:calendar' year_prev month_prev%}">Previous Month</a>
                                            <span style="float:right;">
                                                <a href="{% url 'thelab:calendar' year_next month_next%}">Next Month</a>
                                            </span>
                                            </p>

                                        {{ calendar|safe }}

                                        {{ legend|safe }}

									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Footer -->
				<section id="footer">
					<div class="container">
						<div class="row">
							<div class="col-8 col-12-medium">

								<!-- Links -->
									<section>
										<h2>Links to Important Stuff</h2>
										<div>
											<div class="row">
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
											</div>
										</div>
									</section>

							</div>
							<div class="col-4 col-12-medium imp-medium">

								<!-- Blurb -->
									<section>
										<h2>An Informative Text Blurb</h2>
										<p>
											Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed. Suspendisse eu
											varius nibh. Suspendisse vitae magna eget odio amet mollis. Duis neque nisi,
											dapibus sed mattis quis, sed rutrum accumsan sed. Suspendisse eu varius nibh
											lorem ipsum amet dolor sit amet lorem ipsum consequat gravida justo mollis.
										</p>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Copyright -->
				<div id="copyright">
					&copy; IGLAB. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
				</div>

		</div>

		<!-- Scripts -->
			<script src="{% static 'thelab/js/jquery.min.js' %}"></script>
			<script src="{% static 'thelab/js/browser.min.js' %}"></script>
			<script src="{% static 'thelab/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'thelab/js/util.js' %}"></script>
			<script src="{% static 'thelab/js/main.js' %}"></script>
    {% endblock %}
	</body>
</html>

thelab/templates/thelab/threecolumn.html
<!DOCTYPE HTML>
<!--
	Halcyonic by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Three Column - Halcyonic by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="assets/css/main.css" />
	</head>
	<body class="subpage">
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">
					<div class="container">
						<div class="row">
							<div class="col-12">

								<!-- Logo -->
									<h1><a href="index.html" id="logo">Halcyonic</a></h1>

								<!-- Nav -->
									<nav id="nav">
										<a href="index.html">Homepage</a>
										<a href="threecolumn.html">Three Column</a>
										<a href="twocolumn1.html">Two Column #1</a>
										<a href="twocolumn2.html">Two Column #2</a>
										<a href="onecolumn.html">One Column</a>
									</nav>

							</div>
						</div>
					</div>
				</section>

			<!-- Content -->
				<section id="content">
					<div class="container">
						<div class="row">
							<div class="col-3 col-12-medium">

								<!-- Left Sidebar -->
									<section>
										<header>
											<h2>Ipsum Dolor</h2>
										</header>
										<p>
											Vehicula fermentum ligula at pretium. Suspendisse semper iaculis eros, eu aliquam
											iaculis. Phasellus ultrices diam sit amet orci lacinia sed consequat.
										</p>
										<ul class="link-list">
											<li><a href="#">Sed dolore viverra</a></li>
											<li><a href="#">Ligula non varius</a></li>
											<li><a href="#">Dis parturient montes</a></li>
											<li><a href="#">Nascetur ridiculus</a></li>
										</ul>
									</section>
									<section>
										<header>
											<h2>Magna Phasellus</h2>
										</header>
										<ul class="link-list">
											<li><a href="#">Sed dolore viverra</a></li>
											<li><a href="#">Ligula non varius</a></li>
											<li><a href="#">Nec sociis natoque</a></li>
											<li><a href="#">Penatibus et magnis</a></li>
											<li><a href="#">Dis parturient montes</a></li>
											<li><a href="#">Nascetur ridiculus</a></li>
										</ul>
									</section>
							</div>
							<div class="col-6 col-12-medium imp-medium">

								<!-- Main Content -->
									<section>
										<header>
											<h2>Three Column</h2>
											<h3>A generic three column layout</h3>
										</header>
										<p>
											Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam metus, congue
											vel suscipit ut, dignissim non risus. Vestibulum ante est, fringilla nec placerat
											eu, vestibulum vitae diam. Integer eget egestas eros. Duis enim erat, mollis quis
											lacinia eget, blandit nec ipsum. Donec vitae turpis ipsum. Aliquam mauris libero,
											sagittis in eleifend at, mattis imperdiet velit. Donec urna risus, rutrum molestie
											varius ac, lacinia sit amet augue. Nam ultrices elementum eros.
										</p>
										<p>
											Sed faucibus viverra ligula, non varius magna semper vitae. Donec eu justo ut ipsum
											hendrerit congue nec eu risus. Cum sociis natoque penatibus et magnis dis parturient
											montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing
											egestas tempus. Cras convallis odio sit amet risus convallis porttitor. Integer
											vehicula fermentum ligula at pretium. Suspendisse semper iaculis eros, eu aliquam
											justo imperdiet vel. Proin nec dictum mi. Duis commodo enim non tellus interdum
											elit. Suspendisse fermentum adipiscing nisi, a tempor libero malesuada at. Morbi
											lacinia dui adipiscing risus eleifend tincidunt. Proin eu mauris eu tellus eleifend
											hendrerit.
										</p>
										<p>
											Mauris sit amet tellus urna. In facilisis, tortor vitae ultricies egestas, odio
											mi rhoncus arcu, quis euismod felis felis et velit. Mauris varius consectetur erat
											egestas tempus. Cras convallis odio sit amet risus convallis porttitor. Integer
											vehicula fermentum ligula at pretium. Suspendisse semper iaculis eros, eu aliquam
											justo imperdiet vel. Proin nec dictum mi. Duis commodo enim non tellus interdum
											iaculis. Phasellus ultrices diam sit amet orci lacinia sed consequat dui auctor.
										</p>
									</section>

							</div>
							<div class="col-3 col-12-medium">

								<!-- Right Sidebar -->
									<section>
										<header>
											<h2>Magna Phasellus</h2>
										</header>
										<ul class="link-list">
											<li><a href="#">Sed dolore viverra</a></li>
											<li><a href="#">Ligula non varius</a></li>
											<li><a href="#">Nec sociis natoque</a></li>
											<li><a href="#">Penatibus et magnis</a></li>
											<li><a href="#">Dis parturient montes</a></li>
											<li><a href="#">Nascetur ridiculus</a></li>
										</ul>
									</section>
									<section>
										<header>
											<h2>Ipsum Dolor</h2>
										</header>
										<p>
											Vehicula fermentum ligula at pretium. Suspendisse semper iaculis eros, eu aliquam
											iaculis. Phasellus ultrices diam sit amet orci lacinia sed consequat.
										</p>
										<ul class="link-list">
											<li><a href="#">Sed dolore viverra</a></li>
											<li><a href="#">Ligula non varius</a></li>
											<li><a href="#">Dis parturient montes</a></li>
											<li><a href="#">Nascetur ridiculus</a></li>
										</ul>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Footer -->
				<section id="footer">
					<div class="container">
						<div class="row">
							<div class="col-8 col-12-medium">

								<!-- Links -->
									<section>
										<h2>Links to Important Stuff</h2>
										<div>
											<div class="row">
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
												<div class="col-3 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">Neque amet dapibus</a></li>
														<li><a href="#">Sed mattis quis rutrum</a></li>
														<li><a href="#">Accumsan suspendisse</a></li>
														<li><a href="#">Eu varius vitae magna</a></li>
													</ul>
												</div>
											</div>
										</div>
									</section>

							</div>
							<div class="col-4 col-12-medium imp-medium">

								<!-- Blurb -->
									<section>
										<h2>An Informative Text Blurb</h2>
										<p>
											Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed. Suspendisse eu
											varius nibh. Suspendisse vitae magna eget odio amet mollis. Duis neque nisi,
											dapibus sed mattis quis, sed rutrum accumsan sed. Suspendisse eu varius nibh
											lorem ipsum amet dolor sit amet lorem ipsum consequat gravida justo mollis.
										</p>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Copyright -->
				<div id="copyright">
					&copy; Untitled. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
				</div>

		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>